# Generated by Django 3.1.5 on 2021-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210305_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=10000000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverallReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=10000000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=10000000000, null=True)),
            ],
        ),
    ]
