# Generated by Django 3.1.5 on 2021-03-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210321_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteReport',
        ),
    ]
