# Generated by Django 3.1.5 on 2021-03-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_websitereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('period', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
