# Generated by Django 3.1.5 on 2021-04-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
