# Generated by Django 3.1.5 on 2021-04-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
