# Generated by Django 3.1.5 on 2021-04-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210410_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_added',
        ),
    ]
