# Generated by Django 3.1.5 on 2021-05-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_order_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GetRefund', 'GetRefund'), ('ResendItem', 'ResendItem')], max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('total_value', models.FloatField()),
                ('date', models.DateField(max_length=100, null=True)),
                ('note', models.CharField(max_length=200)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
    ]
