# Generated by Django 3.1.5 on 2021-05-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_returnmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnmanagement',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
