# Generated by Django 3.1.5 on 2021-05-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210518_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnmanagement',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
